<?xml version="1.0" encoding="UTF-8"?><schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:nydatakilde="https://skjema.geonorge.no/SOSI/produktspesifikasjon/dreneringslinjer-med-stikkrenner-nordre-follo/ny-datakilde/1.0" xmlns:sc="http://www.interactive-instruments.de/ShapeChange/AppInfo" elementFormDefault="qualified" targetNamespace="https://skjema.geonorge.no/SOSI/produktspesifikasjon/dreneringslinjer-med-stikkrenner-nordre-follo/ny-datakilde/1.0" version="1.0">
  <import namespace="http://www.interactive-instruments.de/ShapeChange/AppInfo" schemaLocation="https://shapechange.net/resources/schema/ShapeChangeAppinfo.xsd"/>
  <import namespace="http://www.opengis.net/gml/3.2" schemaLocation="http://schemas.opengis.net/gml/3.2.1/gml.xsd"/>
  <!--XML Schema document created by ShapeChange - http://shapechange.net/-->
  <element abstract="true" name="HavnetrafikkFellesegenskaper" substitutionGroup="gml:AbstractFeature" type="nydatakilde:HavnetrafikkFellesegenskaperType">
    <annotation>
      <documentation>abstrakt objekttype som bærer sentrale egenskaper som er anbefalt for bruk i produktspesifikasjoner.

Merknad: Disse egenskapene skal derfor ikke modelleres inn i fagområdemodeller.</documentation>
    </annotation>
  </element>
  <complexType abstract="true" name="HavnetrafikkFellesegenskaperType">
    <complexContent>
      <extension base="gml:AbstractFeatureType">
        <sequence>
          <element name="identifikasjon" type="nydatakilde:IdentifikasjonPropertyType">
            <annotation>
              <documentation>unik identifikasjon av et objekt</documentation>
              <appinfo>
                <sc:taggedValue tag="SOSI_navn">IDENT</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
          <element name="oppdateringsdato" type="date">
            <annotation>
              <documentation>dato for siste endring på objektetdataene

Merknad:
Oppdateringsdato kan være forskjellig fra Datafangsdato ved at data som er registrert kan bufres en kortere eller lengre periode før disse legges inn i datasystemet (databasen).</documentation>
              <appinfo>
                <sc:taggedValue tag="SOSI_navn">OPPDATERINGSDATO</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
        </sequence>
      </extension>
    </complexContent>
  </complexType>
  <complexType name="HavnetrafikkFellesegenskaperPropertyType">
    <sequence minOccurs="0">
      <element ref="nydatakilde:HavnetrafikkFellesegenskaper"/>
    </sequence>
    <attributeGroup ref="gml:AssociationAttributeGroup"/>
    <attributeGroup ref="gml:OwnershipAttributeGroup"/>
  </complexType>
  <element name="Identifikasjon" substitutionGroup="gml:AbstractObject" type="nydatakilde:IdentifikasjonType"/>
  <complexType name="IdentifikasjonType">
    <sequence>
      <element name="lokalId" type="string">
        <annotation>
          <documentation>lokal identifikator av et objekt

Merknad: Det er dataleverendørens ansvar å sørge for at den lokale identifikatoren er unik innenfor navnerommet.</documentation>
          <appinfo>
            <sc:taggedValue tag="SOSI_navn">LOKALID</sc:taggedValue>
          </appinfo>
        </annotation>
      </element>
      <element name="navnerom" type="string">
        <annotation>
          <documentation>navnerom som unikt identifiserer datakilden til et objekt, anbefales å være en http-URI

Eksempel: http://data.geonorge.no/SentraltStedsnavnsregister/1.0

Merknad : Verdien for nanverom vil eies av den dataprodusent som har ansvar for de unike identifikatorene og må være registrert i data.geonorge.no eller data.norge.no</documentation>
          <appinfo>
            <sc:taggedValue tag="SOSI_navn">NAVNEROM</sc:taggedValue>
          </appinfo>
        </annotation>
      </element>
      <element minOccurs="0" name="versjonId" type="string">
        <annotation>
          <documentation>identifikasjon av en spesiell versjon av et geografisk objekt (instans 2025-08-06)</documentation>
          <appinfo>
            <sc:taggedValue tag="SOSI_navn">VERSJONID</sc:taggedValue>
          </appinfo>
        </annotation>
      </element>
    </sequence>
  </complexType>
  <complexType name="IdentifikasjonPropertyType">
    <sequence>
      <element ref="nydatakilde:Identifikasjon"/>
    </sequence>
  </complexType>
  <simpleType name="SjørestriksjonType">
    <annotation>
      <documentation>begrensninger for ferdsel eller bruk av sjøområde

Merknad:
Tilsvarer  RESTRN i S-57


-- Definition - -
limitations on traffic or use of maritime areas.  Note: S-57 RESTRN</documentation>
    </annotation>
    <union memberTypes="nydatakilde:SjørestriksjonEnumerationType nydatakilde:SjørestriksjonOtherType"/>
  </simpleType>
  <simpleType name="SjørestriksjonEnumerationType">
    <annotation>
      <documentation>begrensninger for ferdsel eller bruk av sjøområde

Merknad:
Tilsvarer  RESTRN i S-57


-- Definition - -
limitations on traffic or use of maritime areas.  Note: S-57 RESTRN</documentation>
    </annotation>
    <restriction base="string">
      <enumeration value="ankringForbudt">
        <annotation>
          <documentation>Ankring forbudt</documentation>
        </annotation>
      </enumeration>
      <enumeration value="restriksjonerForAnkring">
        <annotation>
          <documentation>Restriksjoner for ankring</documentation>
        </annotation>
      </enumeration>
      <enumeration value="fiskeErForbudt">
        <annotation>
          <documentation>Fiske er forbudt</documentation>
        </annotation>
      </enumeration>
      <enumeration value="restriksjonerForFiske">
        <annotation>
          <documentation>Restriksjoner for fiske</documentation>
        </annotation>
      </enumeration>
      <enumeration value="trålingErForbudt">
        <annotation>
          <documentation>Tråling er forbudt</documentation>
        </annotation>
      </enumeration>
      <enumeration value="restriksjonerForTråling">
        <annotation>
          <documentation>Restriksjoner for tråling</documentation>
        </annotation>
      </enumeration>
      <enumeration value="&quot;AdgangForbudt-område">
        <annotation>
          <documentation>"Adgang forbudt"-område</documentation>
        </annotation>
      </enumeration>
      <enumeration value="restriksjonerForAdgang">
        <annotation>
          <documentation>Restriksjoner for adgang</documentation>
        </annotation>
      </enumeration>
      <enumeration value="mudringBunnskrapingForbudt">
        <annotation>
          <documentation>Mudring/bunnskraping forbudt</documentation>
        </annotation>
      </enumeration>
      <enumeration value="restriksjonerForBunnskraping">
        <annotation>
          <documentation>Restriksjoner for bunnskraping</documentation>
        </annotation>
      </enumeration>
      <enumeration value="dykkingForbudt">
        <annotation>
          <documentation>Dykking forbudt</documentation>
        </annotation>
      </enumeration>
      <enumeration value="restriksjonerForDykking">
        <annotation>
          <documentation>Restriksjoner for dykking</documentation>
        </annotation>
      </enumeration>
      <enumeration value="sakteFartOgNoWake">
        <annotation>
          <documentation>Sakte fart (og "No Wake")</documentation>
        </annotation>
      </enumeration>
      <enumeration value="områdeSomBørUnngås">
        <annotation>
          <documentation>Område som bør unngås</documentation>
        </annotation>
      </enumeration>
      <enumeration value="forbudMotByggearbeid">
        <annotation>
          <documentation>Forbud mot byggearbeid</documentation>
        </annotation>
      </enumeration>
      <enumeration value="fartBegrenset">
        <annotation>
          <documentation>Fart begrenset</documentation>
        </annotation>
      </enumeration>
    </restriction>
  </simpleType>
  <simpleType name="SjørestriksjonOtherType">
    <restriction base="string">
      <pattern value="other: \w{2,}"/>
    </restriction>
  </simpleType>
  <element name="Trafikkpolititønne" substitutionGroup="nydatakilde:HavnetrafikkFellesegenskaper" type="nydatakilde:TrafikkpolititønneType">
    <annotation>
      <documentation>tønne der trafikkpoliti kan stå og dirigere trafikk</documentation>
    </annotation>
  </element>
  <complexType name="TrafikkpolititønneType">
    <complexContent>
      <extension base="nydatakilde:HavnetrafikkFellesegenskaperType">
        <sequence>
          <element name="posisjon" type="gml:PointPropertyType">
            <annotation>
              <documentation>posisjonen der man ser ut fra tønna</documentation>
            </annotation>
          </element>
          <element name="distrikt" type="gml:CodeType">
            <annotation>
              <appinfo>
                <sc:targetCodeListURI>http://skjema.geonorge.no/SOSI/fagområde/KystOgSjø/4.0/Politidistrikt</sc:targetCodeListURI>
              </appinfo>
            </annotation>
          </element>
        </sequence>
      </extension>
    </complexContent>
  </complexType>
  <complexType name="TrafikkpolititønnePropertyType">
    <sequence minOccurs="0">
      <element ref="nydatakilde:Trafikkpolititønne"/>
    </sequence>
    <attributeGroup ref="gml:AssociationAttributeGroup"/>
    <attributeGroup ref="gml:OwnershipAttributeGroup"/>
  </complexType>
  <element name="TrafikkseparasjonFilDel" substitutionGroup="nydatakilde:HavnetrafikkFellesegenskaper" type="nydatakilde:TrafikkseparasjonFilDelType">
    <annotation>
      <documentation>del av trafikkseparasjonssystem, der trafikkretning er ens


-- Definition --
part of traffic separation system, wherein the direction of traffic is the same</documentation>
    </annotation>
  </element>
  <complexType name="TrafikkseparasjonFilDelType">
    <complexContent>
      <extension base="nydatakilde:HavnetrafikkFellesegenskaperType">
        <sequence>
          <element name="område" type="gml:SurfacePropertyType">
            <annotation>
              <documentation>objektets utstrekning

-- Definition --
area over which an object extends</documentation>
              <appinfo>
                <sc:taggedValue tag="SOSI_navn">Flate</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
          <element name="sjørestriksjon" type="nydatakilde:SjørestriksjonType">
            <annotation>
              <documentation>begrensninger for ferdsel eller bruk av sjøområde

Merknad:
Tilsvarer  RESTRN i S-57

-- Definition --
limitations on traffic or use of maritime areas.  Note: S-57 RESTRN</documentation>
              <appinfo>
                <sc:taggedValue tag="SOSI_navn">SJØ_RESTRIKSJON</sc:taggedValue>
              </appinfo>
            </annotation>
          </element>
        </sequence>
      </extension>
    </complexContent>
  </complexType>
  <complexType name="TrafikkseparasjonFilDelPropertyType">
    <sequence minOccurs="0">
      <element ref="nydatakilde:TrafikkseparasjonFilDel"/>
    </sequence>
    <attributeGroup ref="gml:AssociationAttributeGroup"/>
    <attributeGroup ref="gml:OwnershipAttributeGroup"/>
  </complexType>
</schema>
